"""
This is the template for extracting the solution for the computation problem of computing
a Groebner basis of an indeal in a free algebra over QQ from the output of the computer
algebra system Singular.

.. moduleauthor:: Albert Heinle <albert.heinle@uwaterloo.ca>
"""

from classes.results.compSolutions.FA_Q_dp.FA_Q_dp_SOL import FA_Q_dp_SOL

#--------------------------------------------------
#---------------The template-----------------------
#--------------------------------------------------

def extractSolution(outpString):
    """
    This function extracts the solution of a free algebra Groebner basis
    computation performed in Singular, using the executable code that was
    generated by the template in the same folder on a certain instance.

    :param outpString: The String that was returned by the Singular-execution
    :type  outpString: str
    """
    
    

#--------------------------------------------------
#----------------Help Functions--------------------
#--------------------------------------------------
